### PR TITLE
Grammar improvements (Olli Vanhoja)

### PR DESCRIPTION
**Pull request by matje**
This takes the grammar improvements made by @OlliV almost verbatim.  I removed some punctuation changes because it is debatable what is the best style (I discussed comma usage with some English native speakers). Usually the RFC editor will catch style issues in the AUTH 48 stage.

I added a changelog line and regenerated the output files.

### CODE REVIEW

**Comment by matje** [comment]
This updates #44

**Comment by each** [comment]
> where the presence of other
> -records prevents the use of CNAME.
> +records prevent the use of a CNAME record.

This change is incorrect; the noun phrase "presence of records" is singular
not plural.

Otherwise the PR looks fine to me, though I do have one additional remark:

> -This is enough to be useful by itself.
> +This definition is enough to be useful by itself.

The suggested change is harmless but IMHO the whole paragraph needs rewriting.

**Comment by matje** [comment]
>  where the presence of other
>  -records prevents the use of CNAME.
>  +records prevent the use of a CNAME record.
> 
> This change is incorrect; the noun phrase "presence of records" is singular
> not plural.

Am I missing something? It looks to me that the update changes the plural "prevents" into the singular "prevent".

**Comment by each** [comment]
"Prevent" is the verb in the sentence. When the subject is singular, regular verbs conjugate with an S, but when it's plural, they don't, so you'd say "he prevents", "she prevents", or "it prevents", but "they prevent".

I think the confusion arises from the fact that "records" is plural. But the subject of the sentence is "the presence of other records", which is singular, so the verb should be "prevents".

**Comment by matje** [comment]
Of course. Before I was not caffeinated, and had a terrible headache. Now I am doing much better and it is clear to me. Anyway, I appreciate the English language course :)

**Pull request merged**
